mysql:
    image: mysql:latest
    ports:
        - "3306:3306"
    volumes:
        - ./data:/var/lib/mysql
        - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
        - MYSQL_ROOT_PASSWORD=123456